#!/bin/bash
TAG="$1"; EXTRA="$2"
cd /mnt/disks/scratch/maxtext-1410-upstream
XLAFLAGS="--xla_tpu_dvfs_p_state=7 --xla_tpu_scoped_vmem_limit_kib=65536 --xla_tpu_bf16_emission_mode=NATIVE_EMISSION --xla_tpu_enable_sparse_core_reduce_scatter_v2=true --xla_tpu_enable_sparse_core_collective_offload_all_gather=true --xla_tpu_enable_sparse_core_collective_offload_2d_all_gather=true --xla_tpu_use_tc_device_shape_on_sc=True --xla_sc_disable_megacore_partitioning=True --xla_enable_async_all_gather=true --xla_tpu_enable_sparse_core_collective_offload_all_reduce=true --xla_tpu_enable_sparse_core_collective_offload_reduce_scatter=true --xla_tpu_enable_sparse_core_collective_offload_3d_all_gather=true --xla_tpu_use_single_sparse_core_for_all_gather_offload=true --xla_tpu_enable_concurrent_sparse_core_offloading=true --xla_tpu_aggressive_opt_barrier_removal=true --xla_tpu_enable_offloading_gather_to_sparsecore=true --xla_tpu_enable_sparse_core_collective_aggregator=true --xla_tpu_enable_latency_hiding_layer_scheduler=true --xla_tpu_scheduler_percent_shared_memory_limit=150 --xla_tpu_enable_sparse_core_collective_offload_nd_reduce_scatter=true --xla_tpu_enable_sparse_core_offload_queuing_in_lhs=true"
MT="model_name=deepseek3-671b dtype=bfloat16 per_device_batch_size=1.0 ragged_buffer_factor=2.0 num_moe_token_chunks=2 abort_on_nan_loss=false abort_on_inf_loss=false async_checkpointing=false enable_checkpointing=false remat_policy=custom allow_split_physical_axes=false use_iota_embed=True context=device out_proj=device custom_mesh_and_rule=ep-as-dp decoder_layer_input=device mu_dtype=bfloat16 grad_dtype=bfloat16 dcn_pipeline_parallelism=1 dcn_data_parallelism=-1 ici_pipeline_parallelism=1 ici_fsdp_transpose_parallelism=1 ici_fsdp_parallelism=128 ici_expert_parallelism=8 ici_data_parallelism=1 shard_exp_on_fsdp=false use_custom_sort_vjp=true dataset_type=synthetic dataset_path=gs://max-datasets-rogue opt_type=adamw steps=20 sa_use_fused_bwd_kernel=true use_max_logit_estimate=-1 cost_estimate_flops_fwd=5000000000000 cost_estimate_flops_bwd=5000000000000 float32_weight_sum=False megablox=true sparse_matmul=true use_gmm_v2=true use_tokamax_splash=true use_tokamax_gmm=true wi_tile_fwd_batch_seq=256 wi_tile_fwd_embed_dim=7168 wi_tile_fwd_mlp_dim=1024 wi_tile_dlhs_batch_seq=256 wi_tile_dlhs_embed_dim=3584 wi_tile_dlhs_mlp_dim=2048 wi_tile_drhs_batch_seq=512 wi_tile_drhs_embed_dim=1792 wi_tile_drhs_mlp_dim=2048 wo_tile_fwd_batch_seq=512 wo_tile_fwd_embed_dim=3584 wo_tile_fwd_mlp_dim=2048 wo_tile_dlhs_batch_seq=512 wo_tile_dlhs_embed_dim=1792 wo_tile_dlhs_mlp_dim=2048 wo_tile_drhs_batch_seq=512 wo_tile_drhs_embed_dim=1792 wo_tile_drhs_mlp_dim=2048 sa_block_q=1024 sa_block_kv=1024 sa_block_kv_compute=512 sa_block_q_dkv=1024 sa_block_kv_dkv=1024 sa_block_kv_dkv_compute=1024 sa_fuse_reciprocal=false use_splash_scheduler=true sa_use_base2_exp=true dq_reduction_steps=3 attention=flash max_target_length=4096 use_random_routing=true use_ring_of_experts=true use_ragged_sort=true tokenizer_path=assets/tokenizer.mistral-v3 merge_gating_gmm=false skip_jax_distributed_system=true"
COMPILE="compile_topology=tpu7x-1024 compile_topology_num_slices=1 base_output_directory=/tmp/aot run_name=aot_$TAG"
sudo docker run --rm -v /mnt/disks/scratch/maxtext-1410-upstream/src/maxtext:/deps/src/maxtext:ro \
  -e LIBTPU_INIT_ARGS="$XLAFLAGS" -e JAX_PLATFORMS=cpu -e ENABLE_PJRT_COMPATIBILITY=true \
  gcr.io/tpu-vm-gke-testing/integrate_v2:1410-up2-d59a6a618 \
  python3 -m maxtext.trainers.pre_train.train_compile maxtext/configs/base.yml $MT $EXTRA $COMPILE 2>&1 | grep -iE "temp_size|Finished train_compile|Error|assert|Traceback|ValueError|must divide|OOM|exceed" | tail -12
echo "AOT[$TAG]_exit=${PIPESTATUS[0]}"
